##
## Makefile
##  
## Made by Alex Nelson
## Login   <alextomato3>
##
## Started on  Tue Jan 19 10:46:13 2010 Alex Nelson
TEX=pdflatex
BIB=bibtex
FILE=notes

all:
	$(TEX) $(FILE)
	$(TEX) $(FILE)
bib:
	$(TEX) $(FILE)
	$(BIB) $(FILE)
	$(TEX) $(FILE)
	$(TEX) $(FILE)