##
## Makefile
##  
## Made by Alex Nelson
## Login   <alextomato3>
##
## Started on  Tue Jan  5 11:36:22 2010 Alex Nelson
TEX=pdflatex
BIB=bibtex
FILE=germs
all:
	$(TEX) $(FILE)
	$(BIB) $(FILE)
	$(TEX) $(FILE)
	$(TEX) $(FILE)