##
## Makefile
##  
## Made by Alex Nelson
## Login   <alextomato3>
##
## Started on  Wed Jan 13 16:00:00 2010 Alex Nelson
TEX=pdflatex
FILE=gravityInfo
BIB=bibtex

all:
	$(TEX) $(FILE)
	$(BIB) $(FILE)
	$(TEX) $(FILE)
	$(TEX) $(FILE)