##
## Makefile
##  
## Made by Alex Nelson
## Login   <alextomato3>
##
## Started on  Sun Jan 17 10:27:22 2010 Alex Nelson
TEX=pdflatex
FILE=pseudogroups
BIB=bibtex

all:
	$(TEX) $(FILE)
	$(BIB) $(FILE)
	$(TEX) $(FILE)
	$(TEX) $(FILE)